# Generated by Django 5.0.7 on 2026-07-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planning"),
                    ("IN_PROGRESS", "In Progress"),
                    ("ON_HOLD", "On Hold"),
                    ("COMPLETED", "Completed"),
                    ("ARCHIVED", "Archived"),
                ],
                default="PLANNING",
                max_length=20,
            ),
        ),
    ]
